### ISSUE TITLE
There is no way to auto generate unique filename when uploading file exists!

### ISSUE THREAD

**Issue by soheilyou** [aminyazdanpanah/save-uploaded-files#4]
There is no way to **auto** generate unique filename when uploading file exists! sometimes we don't want to override file and also we don't want to get an  error like:

> Sorry, file already exists

we just want to upload the file and get the uploaded file name!

**Comment by aminyazdanpanah** [comment]
Actually, there is a way to generate a unique filename in this library. You can just use `save_as` key in your config array and generate a unique filename :

``` php
$config_files = [
        [
            'name' => 'upload_images',
            'save_to' => '/the/path/to/directory',
            'save_as' => str_random(),
            'validator' => [
                'min_size' => 10, 
                'max_size' => 1024,
                'allowed_extensions' => ['jpg', 'gif', 'png']
            ],
            'export' => function($filename){return $filename;}
        ]
];

$uploads = uploads($config_files);
```

Also, you can override your file using `override` key in the config array.
Please see [examples](https://github.com/aminyazdanpanah/handling-file-uploads/tree/master/examples) for more information.
If you still have any problem, please post your code here. If not please close this issue
